version: "3.2"

volumes:
  mariadb-glpi:
  glpi:

services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb-glpi
    hostname: mariadb-glpi
    volumes:
      - mariadb-glpi:/config
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=unsafepassword$$
      - TZ=Europe/Brussels
      - MYSQL_DATABASE=glpi
      - MYSQL_USER=glpi_user
      - MYSQL_PASSWORD=glpi
    restart: unless-stopped

  glpi:
    image: ghcr.io/europowergenerators/docker-glpi:main
    container_name: glpi-custom
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=http://localhost:8085
      - TZ=Europe/Brussels
    volumes:
      - glpi:/config
    restart: unless-stopped
